"""Type stubs for bedrock_agentcore module (runtime-only dependency)."""
from typing import Any, Callable

class BedrockAgentCoreApp:
    def __init__(self) -> None: ...
    def entrypoint(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
    def run(self) -> None: ...
