---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow_ref }}-${{ github.ref }}
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy Modifier of Pre Deployment Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step that fails
        run: |
          echo "This workflow is a placeholder and intentionally fails."
          exit 1
name: Deploying Modifier of Pre Deployment Integration Tests
on:
  workflow_dispatch:
    inputs:
      github_hosted:
        default: false
        description: 'Use GitHub-hosted runner instead of ephemeral ECS'
        type: boolean
permissions:
  contents: read
