---
concurrency:
  cancel-in-progress: false
  group: health/terraform.tfstate
jobs:
  assert-no-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install assert-no-comments
        run: |
          python3 -m pip install \
            assert-no-comments
      - name: Assert no comments
        run: >-
          assert-no-comments
          --annotate
          --verbose
          .github/workflows/api_operational_health.yml
          .github/actions/verify-oidc-vars/action.yml
          src/api/operational/health
          lib/python/boto_mocks
          lib/python/lambda_response
          lib/python/module_utils
          lib/python/repo_utils
          lib/python/terraform_config
          lib/python/terraform_drift
          lib/python/test_fixtures
          lib/terraform/common
          test/conftest.py
          test/lib/terraform/conftest.py
          test/api/conftest.py
          test/api/operational/conftest.py
          test/lib/terraform/common
          test/lib/terraform/unit
          test/api/operational/health
          test/lib/python/test_boto_mocks
          test/lib/python/test_lambda_response
          test/lib/python/test_module_utils
          test/lib/python/test_repo_utils
          test/lib/python/test_terraform_config
          test/lib/python/test_terraform_drift
          test/lib/python/test_test_fixtures
  assert-no-inline-directives:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            assert-no-inline-directives
      - name: Assert no inline lint disables
        run: >-
          assert-no-inline-directives
          --tools pylint,mypy,yamllint
          --verbose
          .github/workflows/api_operational_health.yml
          .github/actions/verify-oidc-vars/action.yml
          src/api/operational/health
          lib/python/boto_mocks
          lib/python/lambda_response
          lib/python/module_utils
          lib/python/repo_utils
          lib/python/terraform_config
          lib/python/terraform_drift
          lib/python/test_fixtures
          lib/terraform/common
          test/conftest.py
          test/lib/terraform/conftest.py
          test/api/conftest.py
          test/api/operational/conftest.py
          test/lib/terraform/common
          test/lib/terraform/unit
          test/api/operational/health
          test/lib/python/test_boto_mocks
          test/lib/python/test_lambda_response
          test/lib/python/test_module_utils
          test/lib/python/test_repo_utils
          test/lib/python/test_terraform_config
          test/lib/python/test_terraform_drift
          test/lib/python/test_test_fixtures
  assert-no-linter-config-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            assert-no-linter-config-files
      - name: Assert no linter config files
        run: >-
          assert-no-linter-config-files
          --linters pylint,mypy,yamllint
          --verbose
          src/api/operational/health
          lib/python/boto_mocks
          lib/python/lambda_response
          lib/python/module_utils
          lib/python/repo_utils
          lib/python/terraform_config
          lib/python/terraform_drift
          lib/python/test_fixtures
          test/lib/terraform/common
          test/lib/terraform/unit
          test/api/operational/health
          test/lib/python/test_boto_mocks
          test/lib/python/test_lambda_response
          test/lib/python/test_module_utils
          test/lib/python/test_repo_utils
          test/lib/python/test_terraform_config
          test/lib/python/test_terraform_drift
          test/lib/python/test_test_fixtures
  assert-one-assert-per-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            assert-one-assert-per-pytest
      - name: Assert one assert per pytest
        run: >-
          assert-one-assert-per-pytest
          --verbose
          test/conftest.py
          test/lib/terraform/conftest.py
          test/api/conftest.py
          test/api/operational/conftest.py
          test/lib/terraform/common
          test/lib/terraform/unit
          test/api/operational/health
          test/lib/python/test_boto_mocks
          test/lib/python/test_lambda_response
          test/lib/python/test_module_utils
          test/lib/python/test_repo_utils
          test/lib/python/test_terraform_config
          test/lib/python/test_terraform_drift
          test/lib/python/test_test_fixtures
  assert-opentofu-resource-is-used:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Assert every OpenTofu resource is reached by something
        uses: 10U-Labs/assert-opentofu-resource-is-used@latest
        with:
          directories: >-
            src/api/operational/health
            lib/terraform/common
          search-in: .
          verbose: "true"
  assert-pytest-fixture-name-is-needed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            assert-pytest-fixture-name-is-needed
      - name: Assert pytest fixture name is needed
        run: >-
          assert-pytest-fixture-name-is-needed
          --verbose
          test/conftest.py
          test/lib/terraform/conftest.py
          test/api/conftest.py
          test/api/operational/conftest.py
          test/lib/terraform/common
          test/lib/terraform/unit
          test/api/operational/health
          test/lib/python/test_boto_mocks
          test/lib/python/test_lambda_response
          test/lib/python/test_module_utils
          test/lib/python/test_repo_utils
          test/lib/python/test_terraform_config
          test/lib/python/test_terraform_drift
          test/lib/python/test_test_fixtures
          lib/python/test_fixtures
  assert-python-definition-is-used:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Assert every definition is named outside its own package's tests
        uses: 10U-Labs/assert-python-definition-is-used@latest
        with:
          assume-used-matching: lambda_handler
          dont-search-in: test/lib/python/test_{package}
          search-in: lib/python scripts src test
          trees: >-
            src/api/operational/health/lambda
            lib/python
          verbose: "true"
  assert-python-definition-is-used-in-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Assert every definition in the tests is called
        uses: 10U-Labs/assert-python-definition-is-used@latest
        with:
          assume-used-decorated-with: pytest.fixture
          assume-used-matching: "test_*,Test*,pytest_*"
          search-in: test lib/python scripts src
          trees: >-
            test/conftest.py
            test/lib/terraform/conftest.py
            test/api/conftest.py
            test/api/operational/conftest.py
            test/lib/terraform/common
            test/lib/terraform/unit
            test/api/operational/health
            test/lib/python/test_boto_mocks
            test/lib/python/test_lambda_response
            test/lib/python/test_module_utils
            test/lib/python/test_repo_utils
            test/lib/python/test_terraform_config
            test/lib/python/test_terraform_drift
            test/lib/python/test_test_fixtures
          verbose: "true"
  assert-python-definition-is-used-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Assert every package is imported outside its own tests
        uses: 10U-Labs/assert-python-definition-is-used@latest
        with:
          dont-search-in: test/lib/python/test_{package}
          search-in: lib/python scripts src test
          trees: lib/python
          unimported-packages: "true"
          verbose: "true"
  copy-paste-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jscpd
        run: npm install -g jscpd
      - name: Check for duplicate code in source Python files
        run: |
          jscpd --pattern "**/*.py" --threshold 0 --reporters console \
            src/api/operational/health/lambda/ \
            lib/python/boto_mocks \
            lib/python/lambda_response \
            lib/python/module_utils \
            lib/python/repo_utils \
            lib/python/terraform_config \
            lib/python/terraform_drift \
            lib/python/test_fixtures
  copy-paste-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jscpd
        run: npm install -g jscpd
      - name: Check for duplicate code in test Python files
        run: |
          jscpd --pattern "**/*.py" --threshold 0 --reporters console \
            test/lib/terraform/common \
            test/lib/terraform/unit \
            test/api/operational/health \
            test/lib/python/test_boto_mocks \
            test/lib/python/test_lambda_response \
            test/lib/python/test_module_utils \
            test/lib/python/test_repo_utils \
            test/lib/python/test_terraform_config \
            test/lib/python/test_terraform_drift \
            test/lib/python/test_test_fixtures
  e2e-tests:
    if: github.ref == 'refs/heads/main'
    needs: post-deployment-integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify OIDC variables
        uses: ./.github/actions/verify-oidc-vars
        with:
          aws_region: ${{ vars.AWS_REGION }}
          oidc_role_arn: ${{ vars.OIDC_ROLE_ARN }}
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            requests
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Terraform Init
        run: |
          cd src/api/operational/health && \
            terraform init
      - name: Run E2E tests
        run: |
          BASE=test/api/operational/health
          PYTHONPATH=lib/python python3 -m pytest \
            $BASE/post_deployment/e2e/ \
            --confcutdir=test --verbose --pythonwarnings=error
  mypy-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            boto3-stubs \
            botocore \
            mypy \
            pytest \
            python-hcl2 \
            requests \
            types-requests
      - name: Run mypy on source
        run: |
          MYPYPATH=lib/python python3 -m mypy \
            src/api/operational/health/lambda/handler.py \
            lib/python/boto_mocks \
            lib/python/lambda_response \
            lib/python/module_utils \
            lib/python/repo_utils \
            lib/python/terraform_config \
            lib/python/terraform_drift \
            lib/python/test_fixtures
  mypy-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            boto3-stubs \
            botocore \
            mypy \
            pytest \
            python-hcl2 \
            requests \
            types-requests
      - name: Run mypy on tests
        run: |
          MYPYPATH=lib/python:scripts python3 -m mypy \
            --explicit-package-bases \
            test/conftest.py \
            test/lib/terraform/conftest.py \
            test/api/conftest.py \
            test/api/operational/conftest.py \
            test/lib/terraform/common \
            test/lib/terraform/unit \
            test/api/operational/health \
            test/lib/python/test_boto_mocks \
            test/lib/python/test_lambda_response \
            test/lib/python/test_module_utils \
            test/lib/python/test_repo_utils \
            test/lib/python/test_terraform_config \
            test/lib/python/test_terraform_drift \
            test/lib/python/test_test_fixtures
  post-deployment-integration-tests:
    if: github.ref == 'refs/heads/main'
    needs: reconciliation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify OIDC variables
        uses: ./.github/actions/verify-oidc-vars
        with:
          aws_region: ${{ vars.AWS_REGION }}
          oidc_role_arn: ${{ vars.OIDC_ROLE_ARN }}
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            requests
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Terraform Init
        run: |
          cd src/api/operational/health && \
            terraform init
      - name: Run post-deployment integration tests
        run: |
          BASE=test/api/operational/health
          PYTHONPATH=lib/python python3 -m pytest \
            $BASE/post_deployment/integration/ \
            --confcutdir=test --verbose --pythonwarnings=error
  pre-deployment-integration-tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify OIDC variables
        uses: ./.github/actions/verify-oidc-vars
        with:
          aws_region: ${{ vars.AWS_REGION }}
          oidc_role_arn: ${{ vars.OIDC_ROLE_ARN }}
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            requests
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Terraform Init
        run: |
          cd src/api/operational/health && \
            terraform init
      - name: Run pre-deployment integration tests
        run: |
          BASE=test/api/operational/health
          PYTHONPATH=lib/python python3 -m pytest \
            $BASE/pre_deployment/integration/ \
            --capture=no --confcutdir=test --verbose --pythonwarnings=error
  pylint-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pylint \
            pytest \
            python-hcl2 \
            requests
      - name: Run pylint on source
        run: |
          PYTHONPATH=lib/python python3 -m pylint \
            src/api/operational/health/lambda/handler.py \
            lib/python/boto_mocks \
            lib/python/lambda_response \
            lib/python/module_utils \
            lib/python/repo_utils \
            lib/python/terraform_config \
            lib/python/terraform_drift \
            lib/python/test_fixtures \
            --recursive=y \
            --disable=missing-module-docstring \
            --disable=missing-class-docstring \
            --disable=missing-function-docstring \
            --fail-on=C,R,W \
            --fail-under=10.0
  pylint-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pylint \
            pytest \
            python-hcl2 \
            requests
      - name: Run pylint on tests
        run: |
          PYTHONPATH=lib/python:scripts python3 -m pylint \
            test/conftest.py \
            test/lib/terraform/conftest.py \
            test/api/conftest.py \
            test/api/operational/conftest.py \
            test/lib/terraform/common \
            test/lib/terraform/unit \
            test/api/operational/health \
            test/lib/python/test_boto_mocks \
            test/lib/python/test_lambda_response \
            test/lib/python/test_module_utils \
            test/lib/python/test_repo_utils \
            test/lib/python/test_terraform_config \
            test/lib/python/test_terraform_drift \
            test/lib/python/test_test_fixtures \
            --recursive=y \
            --disable=missing-module-docstring \
            --disable=missing-class-docstring \
            --disable=missing-function-docstring \
            --fail-on=C,R,W --fail-under=10.0
  reconciliation:
    if: >-
      github.ref == 'refs/heads/main'
      && (github.event_name != 'workflow_run'
      || github.event.workflow_run.conclusion == 'success')
    needs:
      - assert-no-comments
      - assert-no-inline-directives
      - assert-no-linter-config-files
      - assert-one-assert-per-pytest
      - assert-opentofu-resource-is-used
      - assert-pytest-fixture-name-is-needed
      - assert-python-definition-is-used
      - assert-python-definition-is-used-in-tests
      - assert-python-definition-is-used-packages
      - copy-paste-source
      - copy-paste-tests
      - mypy-source
      - mypy-tests
      - pre-deployment-integration-tests
      - pylint-source
      - pylint-tests
      - terraform-format
      - terraform-format-module
      - test-boto-mocks
      - test-lambda-response
      - test-module-utils
      - test-repo-utils
      - test-terraform-config
      - test-terraform-drift
      - test-test-fixtures
      - tflint
      - unit-tests
      - unit-tests-module
      - yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify OIDC variables
        uses: ./.github/actions/verify-oidc-vars
        with:
          aws_region: ${{ vars.AWS_REGION }}
          oidc_role_arn: ${{ vars.OIDC_ROLE_ARN }}
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Terraform Init
        run: |
          cd src/api/operational/health && \
            terraform init
      - name: Terraform Plan
        run: |
          cd src/api/operational/health && \
            terraform plan
      - name: Terraform Apply
        run: |
          cd src/api/operational/health && \
            terraform apply -auto-approve
  terraform-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Terraform Format Check
        run: |
          cd src/api/operational/health && \
            terraform fmt -diff -check -recursive
  terraform-format-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Terraform Format Check on common module
        run: |
          cd lib/terraform/common && terraform fmt -diff -check
  test-boto-mocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            requests
      - name: Run boto_mocks tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_boto_mocks/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=boto_mocks \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  test-lambda-response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            requests
      - name: Run lambda_response tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_lambda_response/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=lambda_response \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  test-module-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            requests
      - name: Run module_utils tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_module_utils/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=module_utils \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  test-repo-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            requests
      - name: Run repo_utils tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_repo_utils/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=repo_utils \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  test-terraform-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            requests
      - name: Run terraform_config tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_terraform_config/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=terraform_config \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  test-terraform-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            requests
      - name: Run terraform_drift tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_terraform_drift/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=terraform_drift \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  test-test-fixtures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            pytest-cov \
            python-hcl2 \
            requests
      - name: Run test_fixtures tests with a full coverage gate
        run: |
          PYTHONPATH=lib/python python3 -m pytest \
            test/lib/python/test_test_fixtures/ \
            --confcutdir=test --verbose --pythonwarnings=error \
            --cov=test_fixtures \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  tflint:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify OIDC variables
        uses: ./.github/actions/verify-oidc-vars
        with:
          aws_region: ${{ vars.AWS_REGION }}
          oidc_role_arn: ${{ vars.OIDC_ROLE_ARN }}
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
      - id: terraform
        name: Extract Terraform version
        run: |
          TF_FILE=src/api/operational/health/backend.tf
          TERRAFORM_VERSION=$(grep 'required_version' $TF_FILE \
            | cut -d'"' -f2 | sed 's/>= //')
          echo "version=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform.outputs.version }}
          terraform_wrapper: false
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest
      - name: Terraform Init
        run: |
          cd src/api/operational/health && \
            terraform init
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        name: Run tflint
        run: |
          cd src/api/operational/health && \
            tflint --init && \
            tflint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest \
            requests
      - name: Run unit tests
        run: |
          TEST=test/api/operational/health
          PYTHONPATH=lib/python python3 -m pytest \
            $TEST/pre_deployment/unit/ \
            --confcutdir=test --verbose --pythonwarnings=error
  unit-tests-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            boto3 \
            botocore \
            pytest
      - name: Run module unit tests
        run: |
          TEST_DIRS="test/lib/terraform/common/unit/"
          TEST_DIRS="$TEST_DIRS test/lib/terraform/unit/"
          PYTHONPATH=lib/python python3 -m pytest \
            $TEST_DIRS \
            --confcutdir=test --verbose --pythonwarnings=error
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            yamllint
      - name: Linting YAML files
        run: |
          EMPTY_LINES='empty-lines: {max: 0, max-start: 0, max-end: 1}'
          KEY_ORDERING='key-ordering: enable'
          NEWLINE_AT_EOF='new-line-at-end-of-file: enable'
          TRUTHY='truthy: {allowed-values: ["true", "false", "on"]}'
          RULES="$EMPTY_LINES, $KEY_ORDERING"
          RULES="$RULES, $NEWLINE_AT_EOF, $TRUTHY"
          python3 -m yamllint --strict \
            --config-data "{extends: default, rules: {$RULES}}" \
            .github/workflows/api_operational_health.yml
name: api_operational_health
on:
  push:
    branches:
      - main
    paths:
      - .github/actions/verify-oidc-vars/action.yml
      - .github/workflows/api_operational_health.yml
      - lib/python/boto_mocks/**
      - lib/python/lambda_response/**
      - lib/python/module_utils/**
      - lib/python/repo_utils/**
      - lib/python/terraform_config/**
      - lib/python/terraform_drift/**
      - lib/python/test_fixtures/**
      - lib/terraform/common/**
      - src/api/operational/health/**
      - test/api/conftest.py
      - test/api/operational/conftest.py
      - test/api/operational/health/**
      - test/conftest.py
      - test/lib/python/test_boto_mocks/**
      - test/lib/python/test_lambda_response/**
      - test/lib/python/test_module_utils/**
      - test/lib/python/test_repo_utils/**
      - test/lib/python/test_terraform_config/**
      - test/lib/python/test_terraform_drift/**
      - test/lib/python/test_test_fixtures/**
      - test/lib/terraform/common/**
      - test/lib/terraform/conftest.py
      - test/lib/terraform/unit/**
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    workflows:
      - api_common_routing
permissions:
  contents: read
  id-token: write
