---
concurrency:
  cancel-in-progress: true
  group: documentation-${{ github.ref }}
jobs:
  assert-no-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install assert-no-comments
        run: |
          python3 -m pip install \
            assert-no-comments
      - name: Assert no comments
        run: >-
          assert-no-comments
          --annotate
          --verbose
          .github/workflows/documentation.yml
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          npm install -g markdownlint-cli
          python3 -m pip install \
            assert-no-inline-directives \
            assert-no-linter-config-files
      - if: ${{ !cancelled() }}
        name: Assert no inline markdownlint disables
        run: >-
          assert-no-inline-directives
          --tools markdownlint
          --verbose
          ${{ github.workspace }}
      - if: ${{ !cancelled() }}
        name: Assert no markdownlint config files
        run: >-
          assert-no-linter-config-files
          --linters markdownlint
          --verbose
          ${{ github.workspace }}
      - if: ${{ !cancelled() }}
        name: Lint Markdown
        run: markdownlint '**/*.md' --dot --disable MD013
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          python3 -m pip install \
            assert-no-inline-directives \
            yamllint
      - name: Assert no inline lint disables
        run: >-
          assert-no-inline-directives
          --tools yamllint
          --verbose
          .github/workflows/documentation.yml
      - name: Linting YAML files
        run: |
          EMPTY_LINES='empty-lines: {max: 0, max-start: 0, max-end: 1}'
          KEY_ORDERING='key-ordering: enable'
          NEWLINE_AT_EOF='new-line-at-end-of-file: enable'
          TRUTHY='truthy: {allowed-values: ["true", "false", "on"]}'
          RULES="$EMPTY_LINES, $KEY_ORDERING"
          RULES="$RULES, $NEWLINE_AT_EOF, $TRUTHY"
          python3 -m yamllint --strict \
            --config-data "{extends: default, rules: {$RULES}}" \
            .github/workflows/documentation.yml
name: documentation
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - .github/workflows/documentation.yml
  workflow_dispatch:
permissions:
  contents: read
