---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow_ref }}-${{ github.ref }}
jobs:
  common-vars:
    if: >-
      github.ref == 'refs/heads/main' &&
      (github.event_name != 'workflow_run' ||
       github.event.workflow_run.conclusion == 'success')
    name: Declaring common variables
    outputs:
      aws_region: ${{ steps.shared.outputs.aws_region }}
      role_arn: ${{ steps.shared.outputs.role_arn }}
    runs-on: >-
      ${{ ( vars.USE_GITHUB_HOSTED == 'true' ||
            github.event.inputs.github_hosted == 'true' ||
            contains(github.event.head_commit.message, '[github-hosted]') ||
            contains(github.event.workflow_run.head_commit.message,
              '[github-hosted]') ) &&
          'ubuntu-latest' ||
          fromJSON(format('["ecs", "fargate", "spot", "runner-{0}"]',
            github.run_id)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: shared
        name: Extract shared configuration values
        run: |
          TF_OUTPUTS="lib/terraform/outputs.tf"
          AWS_REGION=$(grep -A1 'output "aws_region"' $TF_OUTPUTS \
            | grep 'value' | cut -d'"' -f2)
          AWS_ACCOUNT_ID=$(grep -A1 'output "aws_account_id"' $TF_OUTPUTS \
            | grep 'value' | cut -d'"' -f2)
          RESOURCE_PREFIX=$(grep -A1 'output "resource_prefix"' $TF_OUTPUTS \
            | grep 'value' | cut -d'"' -f2)
          LOCALS="src/bootstrap/locals.tf"
          ROLE_SUFFIX=$(grep 'name_for_github_actions_role' $LOCALS \
            | sed 's/.*\${local\.resource_prefix}//' | cut -d'"' -f1)
          ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${RESOURCE_PREFIX}${ROLE_SUFFIX}"
          echo "aws_region=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "role_arn=$ROLE_ARN" >> $GITHUB_OUTPUT
  ensuring-endpoint-infrastructure-in-desired-state:
    name: Ensuring endpoint infrastructure is in desired state
    needs:
      - common-vars
      - unit-testing
    permissions:
      contents: read
      id-token: write
    runs-on: >-
      ${{ ( vars.USE_GITHUB_HOSTED == 'true' ||
            github.event.inputs.github_hosted == 'true' ||
            contains(github.event.head_commit.message, '[github-hosted]') ||
            contains(github.event.workflow_run.head_commit.message,
              '[github-hosted]') ) &&
          'ubuntu-latest' ||
          fromJSON(format('["ecs", "fargate", "spot", "runner-{0}"]',
            github.run_id)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ needs.common-vars.outputs.aws_region }}
          role-to-assume: ${{ needs.common-vars.outputs.role_arn }}
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          cd src/api/endpoints/image_for_ec2_runners
          terraform init
      - name: Terraform Apply
        run: |
          cd src/api/endpoints/image_for_ec2_runners
          terraform apply -auto-approve
  integration-testing:
    name: Integration testing
    needs:
      - common-vars
      - ensuring-endpoint-infrastructure-in-desired-state
    permissions:
      contents: read
      id-token: write
    runs-on: >-
      ${{ ( vars.USE_GITHUB_HOSTED == 'true' ||
            github.event.inputs.github_hosted == 'true' ||
            contains(github.event.head_commit.message, '[github-hosted]') ||
            contains(github.event.workflow_run.head_commit.message,
              '[github-hosted]') ) &&
          'ubuntu-latest' ||
          fromJSON(format('["ecs", "fargate", "spot", "runner-{0}"]',
            github.run_id)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ needs.common-vars.outputs.aws_region }}
          role-to-assume: ${{ needs.common-vars.outputs.role_arn }}
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Install Python dependencies
        run: python3 -m pip install pytest boto3
      - name: Run integration tests
        run: |
          ENDPOINT="test/api/endpoints/image_for_ec2_runners/endpoint"
          pytest $ENDPOINT/post_deployment/integration/ \
            --confcutdir=$ENDPOINT -v
  performing-static-analysis:
    name: Performing static analysis
    needs: common-vars
    runs-on: >-
      ${{ ( vars.USE_GITHUB_HOSTED == 'true' ||
            github.event.inputs.github_hosted == 'true' ||
            contains(github.event.head_commit.message, '[github-hosted]') ||
            contains(github.event.workflow_run.head_commit.message,
              '[github-hosted]') ) &&
          'ubuntu-latest' ||
          fromJSON(format('["ecs", "fargate", "spot", "runner-{0}"]',
            github.run_id)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Install linting dependencies
        run: |
          python3 -m pip install pylint mypy yamllint pytest boto3 boto3-stubs
      - name: Linting YAML files
        run: |
          EMPTY_LINES='empty-lines: {max: 0, max-start: 0, max-end: 1}'
          KEY_ORDERING='key-ordering: enable'
          LINE_LENGTH='line-length: disable'
          NEWLINE_AT_EOF='new-line-at-end-of-file: enable'
          TRUTHY='truthy: {allowed-values: ["true", "false", "on"]}'
          RULES="$EMPTY_LINES, $KEY_ORDERING, $LINE_LENGTH"
          RULES="$RULES, $NEWLINE_AT_EOF, $TRUTHY"
          yamllint --strict \
            --config-data "{extends: default, rules: {$RULES}}" \
            .github/workflows/endpoint_v1_image_for_ec2_runners.yml
      - name: Linting Python files
        run: |
          pylint \
            src/api/endpoints/image_for_ec2_runners/lambda/handler.py \
            test/api/endpoints/image_for_ec2_runners/endpoint/ \
            --fail-on=C,R,W \
            --fail-under=10.0
      - name: Static type checking Python files with mypy
        run: |
          SRC="src/api/endpoints/image_for_ec2_runners/lambda/handler.py"
          TEST="test/api/endpoints/image_for_ec2_runners/endpoint/"
          MYPYPATH=lib python3 -m mypy $SRC
          MYPYPATH=lib python3 -m mypy --explicit-package-bases $TEST
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ needs.common-vars.outputs.aws_region }}
          role-to-assume: ${{ needs.common-vars.outputs.role_arn }}
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest
      - name: Terraform Format Check
        run: |
          cd src/api/endpoints/image_for_ec2_runners
          terraform fmt -diff -check -recursive
      - name: Terraform Init
        run: |
          cd src/api/endpoints/image_for_ec2_runners
          terraform init
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        name: Run tflint
        run: |
          cd src/api/endpoints/image_for_ec2_runners && \
            tflint --init && \
            tflint
      - name: Terraform Plan
        run: cd src/api/endpoints/image_for_ec2_runners && terraform plan
  unit-testing:
    name: Unit testing
    needs:
      - common-vars
      - performing-static-analysis
    runs-on: >-
      ${{ ( vars.USE_GITHUB_HOSTED == 'true' ||
            github.event.inputs.github_hosted == 'true' ||
            contains(github.event.head_commit.message, '[github-hosted]') ||
            contains(github.event.workflow_run.head_commit.message,
              '[github-hosted]') ) &&
          'ubuntu-latest' ||
          fromJSON(format('["ecs", "fargate", "spot", "runner-{0}"]',
            github.run_id)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - if: >-
          vars.USE_GITHUB_HOSTED == 'true' ||
          github.event.inputs.github_hosted == 'true' ||
          contains(github.event.head_commit.message, '[github-hosted]') ||
          contains(github.event.workflow_run.head_commit.message,
            '[github-hosted]')
        name: Install Python dependencies
        run: python3 -m pip install pytest boto3
      - name: Run unit tests
        run: |
          ENDPOINT="test/api/endpoints/image_for_ec2_runners/endpoint"
          pytest $ENDPOINT/pre_deployment/ --confcutdir=$ENDPOINT -v
name: Ensuring /v1/image-for-ec2-runners exists and is properly configured
on:
  workflow_call:
    inputs:
      github_hosted:
        default: false
        description: 'Use GitHub-hosted runner instead of ephemeral ECS'
        type: boolean
  workflow_dispatch:
    inputs:
      github_hosted:
        default: false
        description: 'Use GitHub-hosted runner instead of ephemeral ECS'
        type: boolean
permissions:
  contents: read
  id-token: write
