---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow_ref }}-${{ github.ref }}
jobs:
  verify:
    name: Verify RTL
    runs-on: >-
      ${{
        (vars.USE_GITHUB_HOSTED == 'true' ||
         github.event.inputs.github_hosted == 'true' ||
         contains(github.event.head_commit.message, '[github-hosted]'))
        && 'ubuntu-latest'
        || fromJSON(format(
             '["ecs", "fargate", "x86", "spot", "runner-{0}"]',
             github.run_id))
      }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            verilator \
            gcc-riscv64-unknown-elf \
            binutils-riscv64-unknown-elf
      - name: Verify RTL Syntax
        run: make -C src/rtl lint
      - name: Build Simulation
        run: make -C src/rtl build
      - name: Build Test Programs
        run: make -C src/rtl programs
      - name: Run Tests
        run: make -C src/rtl test
      - if: failure()
        name: Upload Waveforms on Failure
        uses: actions/upload-artifact@v4
        with:
          name: waveforms
          path: src/rtl/tb/verilator/*.fst
          retention-days: 7
name: RTL Verilator
on:
  workflow_dispatch:
    inputs:
      github_hosted:
        default: false
        description: 'Use GitHub-hosted runners'
        type: boolean
permissions:
  contents: read
